[project]
name = "leap"
version = "0.1.0"
description = "A fast runner for table reasoning experiments."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datasets>=4.4.1",
    "vllm==0.10.0",
    "PyYAML>=6.0",
]

[dependency-groups]
dev = [
    "pre-commit>=4.5.0",
    "pytest>=9.0.1",
    "pytest-cov>=7.0.0",
]

analysis = [
    "ipykernel",
    "seaborn",
]

[tool.ruff]
line-length = 140
fix = true   # formatter/linter auto-fixes

[tool.ruff.lint]
select = ["E", "F", "I"] # E=pycodestyle, F=pyflakes, I=import sorting