models:
  "Qwen/Qwen2.5-7B-Instruct":
    log_dir: "table_logs_qwen2.5-7B-instruct"
    instruct: true
    hardware:
      num_workers: 1
      tensor_parallel_size: 2
      gpu_allocation: [1,2]
      max_model_len: 32000
    tokenizer:
      llama_tokenizer: true
      closing_quote_token_ids:
        closing_quote_id: 1
        dot_quote_id: 1189
        closing_bracket_quote_id: 9940
        colon_quote_id: 2974
        quote_quote_id: 3014
        list_close_quote_id: 19177
        percent_close_quote_id: 15794
        star_quote_id: 64110
      token_ids:
        comma_id: 11
        list_open_id: 58
  "Qwen/Qwen2.5-32B-Instruct":
    log_dir: "table_logs_qwen2.5-32B-instruct"
    instruct: true
    hardware:
      num_workers: 1
      tensor_parallel_size: 2
      gpu_allocation: [2,3]
      max_model_len: 32000
    tokenizer:
      llama_tokenizer: true
      closing_quote_token_ids:
        closing_quote_id: 1
        dot_quote_id: 1189
        closing_bracket_quote_id: 9940
        colon_quote_id: 2974
        quote_quote_id: 3014
        list_close_quote_id: 19177
        percent_close_quote_id: 15794
        star_quote_id: 64110
      token_ids:
        comma_id: 11
        list_open_id: 58
  "meta-llama/Llama-2-70b-hf":
    log_dir: "table_logs_llama"
    instruct: false
    hardware:
      num_workers: 1
      tensor_parallel_size: 8
      gpu_allocation: [0, 1, 2, 3, 4, 5, 6, 7]
    tokenizer:
      llama_tokenizer: true
      closing_quote_token_ids:
        closing_quote_id: 29908
        dot_quote_id: 1213
        closing_bracket_quote_id: 5513
        colon_quote_id: 6160
        quote_quote_id: 5124
        list_close_quote_id: 18017
        percent_close_quote_id: 23577
        star_quote_id: 20605
      token_ids:
        comma_id: 29892
        list_open_id: 29961

  "meta-llama/Llama-2-70b-chat-hf":
    log_dir: "table_logs_llama"
    instruct: true
    hardware:
      num_workers: 1
      tensor_parallel_size: 8
      gpu_allocation: [0, 1, 2, 3, 4, 5, 6, 7]
    tokenizer:
      llama_tokenizer: true
      closing_quote_token_ids:
        closing_quote_id: 29908
        dot_quote_id: 1213
        closing_bracket_quote_id: 5513
        colon_quote_id: 6160
        quote_quote_id: 5124
        list_close_quote_id: 18017
        percent_close_quote_id: 23577
        star_quote_id: 20605
      token_ids:
        comma_id: 29892
        list_open_id: 29961

  "meta-llama/Llama-4-Scout-17B-16E-Instruct":
    log_dir: "table_logs_llama_4_scout_17b_16e_instruct"
    instruct: true
    hardware:
      num_workers: 1
      tensor_parallel_size: 4
      gpu_allocation: [0, 1, 2, 3]
      max_model_len: 32000
    tokenizer:
      llama_tokenizer: true
      closing_quote_token_ids:
        closing_quote_id: 14
        dot_quote_id: 4743
        closing_bracket_quote_id: 15631
        colon_quote_id: 6624
        quote_quote_id: 7279
        list_close_quote_id: 47014
        percent_close_quote_id: 25122
        star_quote_id: 91406
      token_ids:
        comma_id: 24
        list_open_id: 71
  "gpt2":
    log_dir: "table_logs_gpt2"
    instruct: false
    hardware:
      num_workers: 1
      tensor_parallel_size: 1
      gpu_allocation: [1]
    tokenizer:
      llama_tokenizer: false
      closing_quote_token_ids:
        dot_quote_id: 526
        closing_bracket_quote_id: 16725
        colon_quote_id: 11097
        quote_quote_id: 15931
        list_close_quote_id: 30866
        percent_close_quote_id: 39658
        dash_quote_id: 21215

  "openai/gpt-oss-120b":
    log_dir: "table_logs_gpt_oss"
    instruct: false
    hardware:
      num_workers: 1
      tensor_parallel_size: 4
      gpu_allocation: [0,1,2,3]
    tokenizer:
      llama_tokenizer: false
      closing_quote_token_ids:
        dot_quote_id: 3692
        closing_bracket_quote_id: 22445
        colon_quote_id: 5731
        quote_quote_id: 6371
        list_close_quote_id: 49706
        percent_close_quote_id: 34639
        dash_quote_id: 54284

  "openai/gpt-oss-20b":
    log_dir: "table_logs_gpt_oss_20B"
    instruct: false
    hardware:
      num_workers: 2
      tensor_parallel_size: 2
      gpu_allocation: [0,1,2,3]
    tokenizer:
      llama_tokenizer: false
      closing_quote_token_ids:
        dot_quote_id: 3692
        closing_bracket_quote_id: 22445
        colon_quote_id: 5731
        quote_quote_id: 6371
        list_close_quote_id: 49706
        percent_close_quote_id: 34639
        dash_quote_id: 54284

  "mistralai/Mixtral-8x7B-Instruct-v0.1":
    log_dir: "table_logs_mixtral_instruct"
    instruct: true
    hardware:
      num_workers: 1
      tensor_parallel_size: 1
      gpu_allocation: [2,3]
      max_concurrent_requests: 1
      max_model_len: 32000
    tokenizer:
      llama_tokenizer: true
      closing_quote_token_ids:
        closing_quote_id: 28739
        dot_quote_id: 611
        closing_bracket_quote_id: 12159
        colon_quote_id: 4825
        quote_quote_id: 2539
        star_quote_id: 27045
      token_ids:
        comma_id: 28725
        list_open_id: 28792

  "mistralai/Mixtral-8x7B-v0.1":
    log_dir: "table_logs_mixtral"
    instruct: false
    hardware:
      num_workers: 1
      tensor_parallel_size: 2
      gpu_allocation: [2,3]
    tokenizer:
      llama_tokenizer: true
      closing_quote_token_ids:
        closing_quote_id: 28739
        dot_quote_id: 611
        closing_bracket_quote_id: 12159
        colon_quote_id: 4825
        quote_quote_id: 2539
        star_quote_id: 27045
      token_ids:
        comma_id: 28725
        list_open_id: 28792

  "mistralai/Mistral-7B-Instruct-v0.2":
    log_dir: "table_logs_mixtral-V0.2"
    instruct: true
    hardware:
      num_workers: 1
      tensor_parallel_size: 2
      gpu_allocation: [2,3]
      max_model_len: 32000
    tokenizer:
      llama_tokenizer: true
      closing_quote_token_ids:
        closing_quote_id: 28739
        dot_quote_id: 611
        closing_bracket_quote_id: 12159
        colon_quote_id: 4825
        quote_quote_id: 2539
        star_quote_id: 27045
      token_ids:
        comma_id: 28725
        list_open_id: 28792
